version: '3.7'

volumes:
    grafana_data: {}
    victoria_metrics_data: {}

networks:
  yearn-exporter:

services:
  yearn-exporter-v1:
    build: .
    command: exporter_v1
    ports:
      - 8800:8800
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-v2:
    build: .
    command: exporter_v2
    ports:
      - 8801:8801
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-iearn:
    build: .
    command: exporter_iearn
    ports:
      - 8802:8802
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-ironbank:
    build: .
    command: exporter_ironbank
    ports:
      - 8803:8803
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-experimental:
    build: .
    command: exporter_experimental
    ports:
      - 8804:8804
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  vmagent:
    image: victoriametrics/vmagent
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '-promscrape.config=/etc/prometheus/prometheus.yml'
      - '-remoteWrite.url=http://victoria-metrics:8428/api/v1/write'
    links:
      - victoria-metrics:victoria-metrics
    depends_on:
      - victoria-metrics
    networks:
      - yearn-exporter
    restart: always

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.49.0
    volumes:
      - victoria_metrics_data:/victoria-metrics-data
    ports:
      - 8428:8428
    networks:
      - yearn-exporter
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - victoria-metrics
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/v1_vaults.json
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - yearn-exporter
    restart: always
